[project]
name = "python-fs-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "e2b>=2.7.0",
    "e2b-code-interpreter>=2.3.0",
    "python-dotenv>=1.2.1",
    "redis>=7.1.0",
]
