# This is a config for E2B sandbox template.
# You can use template ID (pqsrmfvnqkmolnlvkan5) or template name (react-fast-mongo-pre-v0) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("react-fast-mongo-pre-v0") # Sync sandbox
# sandbox = await AsyncSandbox.create("react-fast-mongo-pre-v0") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('react-fast-mongo-pre-v0')

team_id = "e66bba55-d673-4ef7-bc35-4e6e172ca213"
memory_mb = 4_096
cpu_count = 4
dockerfile = "e2b.Dockerfile"
template_name = "react-fast-mongo-pre-v0"
template_id = "pqsrmfvnqkmolnlvkan5"
